[project]
name = "poetry-dir"
version = "0.1.0"
description = ""
authors = [
    {name = "jtott"}
]
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "google-cloud-pipeline-components (>=2.19.0,<3.0.0)",
    "google-cloud-aiplatform (==1.85.0)",
    "google-cloud-bigquery (>=3.31.0,<4.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "db-dtypes (>=1.4.2,<2.0.0)",
    "plotly (>=6.0.1,<7.0.0)",
    "kfp (==2.10.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
